import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { siteConfig } from '@/config/site.config';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    default: siteConfig.name,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  metadataBase: new URL(siteConfig.url),
  // Static icons generated by scripts/generate-brand-assets.ts from
  // siteConfig.  Run `npm run generate-icons` to regenerate, or it
  // auto-runs on dev/build via the predev / prebuild hooks.
  //
  // Order matters: PNG entries come BEFORE the SVG entry.  Googlebot
  // currently can't render SVG favicons reliably — if it sees the SVG
  // first it ends up showing no favicon in SERPs.  PNG → ICO → SVG
  // makes Google pick a working PNG and lets modern browsers prefer
  // the crisp SVG.
  icons: {
    icon: [
      { url: '/favicon-48x48.png', sizes: '48x48', type: 'image/png' },
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
      { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/favicon.ico', sizes: 'any', type: 'image/x-icon' },
      { url: '/favicon.svg', type: 'image/svg+xml' },
    ],
    apple: '/apple-touch-icon.png',
  },
  manifest: '/site.webmanifest',
  // Resolved relative to metadataBase, so each page emits a canonical /
  // og:url that matches its own pathname instead of the homepage URL.
  // Page-level generateMetadata can override these with absolute URLs
  // where needed.
  alternates: {
    canonical: './',
  },
  // OG & Twitter images are auto-discovered from opengraph-image.tsx
  // and twitter-image.tsx co-located with this layout.  Those files
  // are pre-rendered at build time, so Twitter/X gets a static PNG
  // instantly (no dynamic rendering timeout).  Only the text metadata
  // is set here.
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: './',
    siteName: siteConfig.name,
    title: siteConfig.name,
    description: siteConfig.description,
  },
  twitter: {
    card: 'summary_large_image',
    site: siteConfig.seo.twitterHandle || undefined,
    creator: siteConfig.seo.twitterHandle || undefined,
    title: siteConfig.name,
    description: siteConfig.description,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/*
         * Google tag (gtag.js) — loaded in <head> so Tag Assistant
         * detects it.  Both GA and Google Ads share the same gtag.js
         * snippet, so one async <script> covers both.
         */}
        {process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID && (
          <>
            <script
              async
              src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}`}
            />
            <script
              dangerouslySetInnerHTML={{
                __html: `
                  window.dataLayer = window.dataLayer || [];
                  function gtag(){dataLayer.push(arguments);}
                  gtag('js', new Date());
                  gtag('config', '${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}');
                  ${process.env.NEXT_PUBLIC_GOOGLE_ADS_ID ? `gtag('config', '${process.env.NEXT_PUBLIC_GOOGLE_ADS_ID}');` : ''}
                `,
              }}
            />
          </>
        )}
        {/*
         * Duplicate the metadata.icons entries inline because some
         * crawlers (notably older Googlebot) only inspect raw <head>
         * markup, not Next.js's hydrated metadata output.  Same
         * PNG-first, SVG-last order as in the metadata above.
         */}
        <link rel="icon" href="/favicon-48x48.png" type="image/png" sizes="48x48" />
        <link rel="icon" href="/favicon-32x32.png" type="image/png" sizes="32x32" />
        <link rel="icon" href="/favicon-16x16.png" type="image/png" sizes="16x16" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
